import os
import time
import logging

# Логи в домашней директории
LOG_DIR = os.path.expanduser("~/.local/share/bras-autotune")
LOG_PATH = os.path.join(LOG_DIR, "bras-autotune.log")
os.makedirs(LOG_DIR, exist_ok=True)

logging.basicConfig(
    filename=LOG_PATH,
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s"
)


def ensure_dir(path):
    """Создаёт директорию, если её нет."""
    if not os.path.exists(path):
        os.makedirs(path, exist_ok=True)
        logging.info(f"Created directory: {path}")


def backup_file(path):
    """Создаёт бэкап, если файл существует."""
    if os.path.exists(path):
        ts = time.strftime("%Y%m%d-%H%M%S")
        backup = f"{path}.backup-{ts}"
        os.rename(path, backup)
        logging.info(f"Backup created: {backup}")


def generate_interfaces_cfg(cfg):
    """Генерирует конфиг для /etc/network/interfaces.d/bras.conf"""
    return f"""
# Auto-generated by bras-autotune
# WAN: {cfg['if_wan']}
# BRAS: {cfg['if_bras']}
# DATA cores: {cfg['data_cores']}
# CPU mask: {cfg['data_mask_hex']}

auto {cfg['if_wan']}
iface {cfg['if_wan']} inet manual
    up ethtool -L {cfg['if_wan']} combined {cfg['rxq_wan']}
    up taskset -p 0x{cfg['data_mask_hex']} $(pidof pppoe-server || true)

auto {cfg['if_bras']}
iface {cfg['if_bras']} inet manual
    up ethtool -L {cfg['if_bras']} combined {cfg['rxq_bras']}
    up taskset -p 0x{cfg['data_mask_hex']} $(pidof accel-ppp || true)
"""


def generate_user_cfg(cfg):
    """Генерирует текстовый отчёт для пользовательских директорий."""
    return f"""
BRAS AUTOTUNE RESULT
====================

WAN interface:      {cfg['if_wan']}
BRAS interface:     {cfg['if_bras']}
DATA-plane cores:   {cfg['data_cores']}
CPU mask (hex):     {cfg['data_mask_hex']}

WAN RX queues:      {cfg['rxq_wan']}
BRAS RX queues:     {cfg['rxq_bras']}

DATA CPU list:      {cfg['data_cpu_list']}
CTRL CPU list:      {cfg['ctrl_cpu_list']}

Output directory:   {cfg['out_dir']}
"""


def generate_config(cfg):
    """
    Основная функция генерации конфигурации.
    Возвращает путь к созданному файлу.
    """

    out_dir = cfg["out_dir"]
    ensure_dir(out_dir)

    # -----------------------------
    # /etc/network/interfaces.d mode
    # -----------------------------
    if cfg["etc_mode"]:
        path = os.path.join(out_dir, "bras.conf")

        backup_file(path)
        content = generate_interfaces_cfg(cfg)

        with open(path, "w") as f:
            f.write(content)

        logging.info(f"Generated system config: {path}")
        return path

    # -----------------------------
    # User mode (~/bras-autotune or /tmp)
    # -----------------------------
    path = os.path.join(out_dir, "bras-autotune.txt")

    backup_file(path)
    content = generate_user_cfg(cfg)

    with open(path, "w") as f:
        f.write(content)

    logging.info(f"Generated user config: {path}")
    return path
